### ISSUE TITLE
illegal instruction

### ISSUE THREAD

**Issue by bigcat88** [mrecachinas/hexhamming#14]
@mrecachinas here is pull request #13. are you alive? =)

**Comment by mrecachinas** [comment]
Sorry about the delay -- I need to setup CI on PRs. I just merged it, but it looks like it's still getting an illegal instruction: https://github.com/mrecachinas/hexhamming/actions/runs/1554418022.

**Comment by bigcat88** [comment]
ok, i will in a few hours at it...

**Comment by bigcat88** [comment]
@mrecachinas i rewrite last pull request, now it is fine. #16
if you wish i can rewrite CI to use cibuildwheel.
