### ISSUE TITLE
Document check_bytes_arrays_within_dist

### ISSUE THREAD

**Issue by RandomNameUser** [mrecachinas/hexhamming#22]
I was looking into how to add something like this, and found that it's already there, but you have to look into the (admittedly short) source to find it. Please add a simple example to the docs on how to use it. Thanks!

**Comment by mrecachinas** [comment]
👋 Thanks for the feedback! Take a look at #24 to see if the example is helpful and what you expect. If so, go ahead and approve the PR and I'll merge it.
