### ISSUE TITLE
Add function to find closest bytestring/string in list

### ISSUE THREAD

**Issue by mrecachinas** [mrecachinas/hexhamming#9]
In #7, @bigcat88 wrote:

> Also imho, will be interesting such function for python:
> ```
> int check_bytes_arrays_within_dist(
>     byte* arrays_to_compare,
>     int nElementsInFirstArg,
>     byte* what_to_compare,
>     int nBytesInElement,
>     int max_dist
> )
>```
> Return index of first array for which distance <(or <=) max_dist, or -1 otherwise.
>
> Like current `check_hexstrings_within_dist` with ability to compare many arrays(arg1) to one(arg=what_to_compare) to see if for specified distance there is any equality.
> Thanks, for your work and library - anyway 👍

**Comment by bigcat88** [comment]
```
static char check_bytes_arrays_within_dist_docstring[] =
    "Check if any element of byte array are within a specified Hamming Distance\n"
    "and return it's index or -1 otherwise.\n\n"
    "Size in bytes of `array_of_elems` and `elem_to_compare` must be multiple of 16."
    "Size in bytes of array_of_elems must be equal to `elem_size` * `elem_count`. \n\n"
    ":param elem_size: size in bytes of one element of array\n"
    ":type elem_size: int\n"
    ":param elem_count: number of elements in array_of_elems to search within\n"
    ":type elem_count: int\n"
    ":param array_of_elems: array of bytes to search within\n"
    ":type array_of_elems: bytes\n"
    ":param elem_to_compare: will compare to each element in array_of_elems\n"
    ":type elem_to_compare: bytes\n"
    ":param max_dist: maximum allowable Hamming Distance\n"
    ":type max_dist: int\n"
    ":returns: index of first element in array_of_elems for which hamming distance <= `max_dist` or -1. \n"
    ":rtype: int\n"
    ":raises nothing: if input parameters are invalid, internal exception will occur. Use wisely!"
```

I can write such function. Do you ok with this?


Also, have you any plans to build binary wheels for different OS?(Centos,Debian,Ubuntu)(manylinux1-..-manylinux_x_y) ?

**Comment by mrecachinas** [comment]
Definitely happy to support as many platforms as possible!

Also very happy to have you add that function! That signature looks good to me.

**Comment by bigcat88** [comment]
Done it locally on my mac, need only understand how to add tests and benchmarks.
After that will push it to my github and make a pull request...

**Comment by bigcat88** [comment]
Is there any problems with my pull request?

**Comment by mrecachinas** [comment]
Ah sorry! I didn’t get notified that there was a PR. I’ll review it this morning.

**Comment by bigcat88** [comment]
I will rewrite maybe code for non SSE, need look deeper at it, it seems not so optimised for my func when it takes array with multiply 16.(i just copied your code)
And add Py_BEGIN_ALLOW_THREADS/Py_END_ALLOW_THREADS at my fun.
But it will be later, first when I have time(probably on Monaday-Wednesday), with next pull request I plan to add building wheels.
Like this, but with more wheels and with python 3.9 support:
[https://github.com/carsales/pyheif/blob/38468c5963f7c7e40f482c71d9662f9c7412895f/docker/Dockerfile.manylinux2014#L165](url)

**Comment by mrecachinas** [comment]
Sounds good. I'd like to tie the wheel-building and pushing to PyPI with GitHub Actions (probably using this action https://github.com/RalfG/python-wheels-manylinux-build). I can try to add that today.

**Comment by bigcat88** [comment]
> Sounds good. I'd like to tie the wheel-building and pushing to PyPI with GitHub Actions (probably using this action https://github.com/RalfG/python-wheels-manylinux-build). I can try to add that today.

Looks very promising, if I can help with this - just say.

**Comment by bigcat88** [comment]
Say if there is anything else that I can put for that pull request.
When binary wheels(manylinux2014/manylinux2010) will appear, I can test them on different CPUs(with/without AVX support), but  pretty sure there will not be any problems.

**Comment by mrecachinas** [comment]
I'll need to spend a little more time on the wheel building for i686 and ARM, but manylinux wheels are now being built in CI as of https://github.com/mrecachinas/hexhamming/commit/4fc4fb8a054a28594ec5b36dc2764a804522e452. For some reason, I'm getting a Docker compatibility error with ARM: https://github.com/mrecachinas/hexhamming/runs/3526835994?check_suite_focus=true. Error copied below:

```
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64)
and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by mrecachinas** [comment]
Closing this since #10 has been pulled in and passed CI. For further optimizations, just go ahead and submit a PR! 😄
